<?php

namespace Tests\Unit\Http\Requests\Policies;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Policies\AdminUpdatePolicy
 */
class AdminUpdatePolicyTest extends TestCase
{
    /** @var \App\Http\Requests\Policies\AdminUpdatePolicy */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Policies\AdminUpdatePolicy();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'policy.title' => 'required|max:255',
            'policy.date' => 'required|date',
            'policy.live' => 'boolean',
        ], $actual);
    }

    // test cases...
}
