<?php

namespace Tests\Unit\Http\Requests\Organization;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Organization\UpdateOrganizationRequest
 */
class UpdateOrganizationRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Organization\UpdateOrganizationRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Organization\UpdateOrganizationRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'organization.description' => 'required|string',
            'organization.url' => 'url|nullable',
            'organization.live' => 'boolean',
            'image' => 'file|nullable',
        ], $actual);
    }

    // test cases...
}
