<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AdminFeatureController
 */
class AdminFeatureControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin_feature_create'));

        $response->assertOk();
        $response->assertViewIs('admin.feature');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $feature = \App\Models\Feature::factory()->create();

        $response = $this->delete(route('admin_feature_destroy'));

        $response->assertRedirect(route('admin_features_list'));
        $this->assertDeleted($adminFeatureDestroy);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminFeatureController::class,
            'destroy',
            \App\Http\Requests\Feature\DestroyFeatureRequest::class
        );
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $feature = \App\Models\Feature::factory()->create();

        $response = $this->get(route('admin_feature_edit', ['any_feature' => $any_feature]));

        $response->assertOk();
        $response->assertViewIs('admin.feature');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $features = \App\Models\Feature::factory()->times(3)->create();

        $response = $this->get(route('admin_features_list'));

        $response->assertOk();
        $response->assertViewIs('admin.features-list');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('admin/feature/create', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin_feature_edit', [$feature->slug]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminFeatureController::class,
            'store',
            \App\Http\Requests\Feature\StoreFeatureRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $feature = \App\Models\Feature::factory()->create();

        $response = $this->post('admin/feature/{any_feature}/edit', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin_feature_edit', [$any_feature->slug]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminFeatureController::class,
            'update',
            \App\Http\Requests\Feature\UpdateFeatureRequest::class
        );
    }

    // test cases...
}
