<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AdminByLawController
 */
class AdminByLawControllerTest extends TestCase
{
    //use RefreshDatabase;

    /**
     * @test
     *
     */
    public function create_returns_an_ok_response()
    {
        $response = $this->actingAs($this->admin_user)->get(route('admin_bylaw_create'));

        $response->assertOk();
        $response->assertViewIs('admin.bylaw');
        $response->assertViewHas('data');
    }

    /**
     * @test
     * @group destroy
     */
    public function destroy_returns_an_ok_response()
    {
        $bylaw = \App\Models\Bylaw::factory()->create();
        $response = $this->actingAs($this->admin_user)->delete(route('admin_bylaw_destroy'), ['ids' => $bylaw->id]);
        $this->assertModelMissing($bylaw);
        $response->assertRedirect(route('admin_bylaws_list'));
    }

    /**
     * @test
     * @group
     */
    public function destroy_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminByLawController::class,
            'destroy',
            \App\Http\Requests\Bylaws\DestroyBylawRequest::class
        );
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $bylaw = \App\Models\Bylaw::factory()->create();

        $response = $this->get(route('admin_bylaw_edit', ['any_bylaw' => $any_bylaw]));

        $response->assertOk();
        $response->assertViewIs('admin.bylaw');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $bylaws = \App\Models\Bylaw::factory()->times(3)->create();

        $response = $this->get(route('admin_bylaws_list'));

        $response->assertOk();
        $response->assertViewIs('admin.bylaws_list');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('admin/bylaw/create', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin_bylaw_edit', [$bylaw->id]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminByLawController::class,
            'store',
            \App\Http\Requests\Bylaws\StoreBylawRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $bylaw = \App\Models\Bylaw::factory()->create();

        $response = $this->post('admin/bylaw/{any_bylaw}/edit', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin_bylaw_edit', [$any_bylaw->id]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminByLawController::class,
            'update',
            \App\Http\Requests\Bylaws\UpdateBylawRequest::class
        );
    }

    // test cases...
}
