<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AdminEmploymentController
 */
class AdminEmploymentControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin_employment_create'));

        $response->assertOk();
        $response->assertViewIs('admin.employment');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $employment = \App\Models\Employment::factory()->create();

        $response = $this->delete(route('admin_employment_destroy'));

        $response->assertRedirect(route('admin_employment_list'));
        $this->assertDeleted($adminEmploymentDestroy);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminEmploymentController::class,
            'destroy',
            \App\Http\Requests\Employment\DestroyEmploymentRequest::class
        );
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $employment = \App\Models\Employment::factory()->create();

        $response = $this->get(route('admin_employment_edit', ['any_employment' => $any_employment]));

        $response->assertOk();
        $response->assertViewIs('admin.employment');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $employments = \App\Models\Employment::factory()->times(3)->create();

        $response = $this->get(route('admin_employment_list'));

        $response->assertOk();
        $response->assertViewIs('admin.employment_list');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('admin/employment/create', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin_employment_edit', [$employment->id]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminEmploymentController::class,
            'store',
            \App\Http\Requests\Employment\StoreEmploymentRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $employment = \App\Models\Employment::factory()->create();

        $response = $this->post('admin/employment/{any_employment}/edit', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin_employment_edit', [$any_employment->id]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminEmploymentController::class,
            'update',
            \App\Http\Requests\Employment\UpdateEmploymentRequest::class
        );
    }

    // test cases...
}
