<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AdminAgreementController
 */
class AdminAgreementControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $organizations = \App\Models\Organization::factory()->times(3)->create();
        $venues = \App\Models\Venue::factory()->times(3)->create();

        $response = $this->get(route('agreement_create'));

        $response->assertOk();
        $response->assertViewIs('admin.agreement');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $agreement = \App\Models\Agreement::factory()->create();

        $response = $this->delete(route('agreement_destroy'));

        $response->assertRedirect(route('agreements_list'));
        $this->assertDeleted($agreementDestroy);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminAgreementController::class,
            'destroy',
            \App\Http\Requests\Agreements\DestroyAgreementRequest::class
        );
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $agreement = \App\Models\Agreement::factory()->create();
        $organizations = \App\Models\Organization::factory()->times(3)->create();
        $venues = \App\Models\Venue::factory()->times(3)->create();

        $response = $this->get(route('agreement_edit', ['any_agreement' => $any_agreement]));

        $response->assertOk();
        $response->assertViewIs('admin.agreement');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $agreements = \App\Models\Agreement::factory()->times(3)->create();

        $response = $this->get(route('agreements_list'));

        $response->assertOk();
        $response->assertViewIs('admin.agreements_list');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('admin/agreement/create', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('agreement_edit', [$agreement->id]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminAgreementController::class,
            'store',
            \App\Http\Requests\Agreements\StoreAgreementRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $agreement = \App\Models\Agreement::factory()->create();

        $response = $this->post('admin/agreement/{any_agreement}/edit', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('agreement_edit', [$any_agreement->id]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminAgreementController::class,
            'update',
            \App\Http\Requests\Agreements\UpdateAgreementRequest::class
        );
    }

    // test cases...
}
