<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AdminExecutiveMembershipController
 */
class AdminExecutiveMembershipControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $executives = \App\Models\Executive::factory()->times(3)->create();

        $response = $this->get(route('admin_executive_create', [$user]));

        $response->assertOk();
        $response->assertViewIs('admin.executive');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $executiveMembership = \App\Models\ExecutiveMembership::factory()->create();

        $response = $this->delete(route('admin_executive_destroy'));

        $response->assertRedirect(route('admin_executives'));
        $this->assertDeleted($adminExecutiveDestroy);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminExecutiveMembershipController::class,
            'destroy',
            \App\Http\Requests\Executive\DestroyAdminExecutiveMembership::class
        );
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $executiveMembership = \App\Models\ExecutiveMembership::factory()->create();
        $executives = \App\Models\Executive::factory()->times(3)->create();

        $response = $this->get(route('admin_executive_edit', [$executiveMembership]));

        $response->assertOk();
        $response->assertViewIs('admin.executive');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin_executives_list'));

        $response->assertOk();
        $response->assertViewIs('admin.executives_list');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();

        $response = $this->post('admin/user/{user}/executiveMembership/create', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin_executive_edit', $executiveMembership->id));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminExecutiveMembershipController::class,
            'store',
            \App\Http\Requests\Executive\StoreAdminExecutiveMembership::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $executiveMembership = \App\Models\ExecutiveMembership::factory()->create();

        $response = $this->post('admin/executiveMembership/{executiveMembership}/edit', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin_executive_edit', $executiveMembership->id));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AdminExecutiveMembershipController::class,
            'update',
            \App\Http\Requests\Executive\UpdateAdminExecutiveMembership::class
        );
    }

    // test cases...
}
