<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AgreementController
 */
class AgreementControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function list_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $agreements = \App\Models\Agreement::factory()->times(3)->create();

        $response = $this->get(route('agreements_list_public'));

        $response->assertOk();
        $response->assertViewIs('agreements_list');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $agreement = \App\Models\Agreement::factory()->create();

        $response = $this->get(route('agreement_show', [$agreement]));

        $response->assertOk();
        $response->assertViewIs('agreement_view');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    // test cases...
}
