<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AttachmentController
 */
class AttachmentControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('attachment_create'));

        $response->assertOk();
        $response->assertViewIs('admin.attachment');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $attachment = \App\Models\Attachment::factory()->create();

        $response = $this->delete(route('attachment_destroy'));

        $response->assertRedirect(route('attachments_list'));
        $this->assertDeleted($attachmentDestroy);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AttachmentController::class,
            'destroy',
            \App\Http\Requests\Attachments\DestroyAttachmentRequest::class
        );
    }

    /**
     * @test
     */
    public function download_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $attachment = \App\Models\Attachment::factory()->create();

        $response = $this->get(route('attachment_download', ['folder' => $attachment->folder, $attachment]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $attachment = \App\Models\Attachment::factory()->create();

        $response = $this->get(route('admin_attachment_edit', [$attachment]));

        $response->assertRedirect(route('attachments_list'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $attachment = \App\Models\Attachment::factory()->create();
        $attachments = \App\Models\Attachment::factory()->times(3)->create();

        $response = $this->get(route('attachments_list'));

        $response->assertOk();
        $response->assertViewIs('admin.list_attachments');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('admin/attachment/create', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin_attachment_edit', $attachment->id));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AttachmentController::class,
            'store',
            \App\Http\Requests\Attachments\StoreAttachmentRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $attachment = \App\Models\Attachment::factory()->create();

        $response = $this->post('admin/attachment/{attachment}/edit', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin_attachment_edit', $attachment->id));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\AttachmentController::class,
            'update',
            \App\Http\Requests\Attachments\UpdateAttachmentRequest::class
        );
    }

    // test cases...
}
