<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ContactController
 */
class ContactControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contact = \App\Models\Contact::factory()->create();
        $pages = \App\Models\Page::factory()->times(3)->create();

        $response = $this->get(route('contact'));

        $response->assertOk();
        $response->assertViewIs('contact');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function submit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('contact', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('contact'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function submit_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\ContactController::class,
            'submit',
            \App\Http\Requests\Contact\SubmitContact::class
        );
    }

    // test cases...
}
