<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MemoriamController
 */
class MemoriamControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $memoriams = \App\Models\Memoriam::factory()->times(3)->create();

        $response = $this->get(route('memoriam_list'));

        $response->assertOk();
        $response->assertViewIs('memoriams');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $memoriam = \App\Models\Memoriam::factory()->create();

        $response = $this->get(route('memoriam', [$memoriam]));

        $response->assertOk();
        $response->assertViewIs('memoriam');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    // test cases...
}
