<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\PostController
 */
class PostControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function list_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $posts = \App\Models\Post::factory()->times(3)->create();

        $response = $this->get(route('posts'));

        $response->assertOk();
        $response->assertViewIs('posts');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $post = \App\Models\Post::factory()->create();

        $response = $this->get(route('post_show', [$post]));

        $response->assertRedirect('login');

        // TODO: perform additional assertions
    }

    // test cases...
}
