<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;


/**
 * @see \App\Http\Controllers\UserController
 */
class UserControllerTest extends TestCase
{
    //use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        //$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        // TODO: perform additional assertions

        $this->user->load('user_info', 'phone_number', 'membership');
        $this->user->assignRole('member');

        $response = $this->actingAs($this->user)->get(route('members'));
        $response->assertOk();
        $response->assertViewIs('listusers');
        $response->assertViewHas('data');

    }

    /**
     * @test
     */
    public function not_authenticated_index_returns_a_response()
    {
        //$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        // TODO: perform additional assertions

        $this->user->load('user_info', 'phone_number', 'membership');
        $this->user->assignRole('member');

        $response = $this->get(route('members'));
        $response->assertStatus(302);
        //todo alternative to hard coded status

    }



    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
       //$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $authUser = $this->user;

       // $this->user->assignRole('super-admin');

        $response = $this->actingAs($authUser)->get(route('member_edit', [$authUser]));

        $response->assertOk();
        $response->assertViewIs('member_edit');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_address_returns_an_ok_response()
    {
        //$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $authUser = $this->user;

        $response = $this->actingAs($authUser)->get(route('member_address_edit', [$authUser]));

        $response->assertOk();
        $response->assertViewIs('member_address_edit');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_emergency_contact_returns_an_ok_response()
    {
        //$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $authUser = $this->user;

        $response = $this->actingAs($authUser)->get(route('edit_emergency_contact', [$authUser]));

        $response->assertOk();
        $response->assertViewIs('member_emergency_edit');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_password_returns_an_ok_response()
    {
       // $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
        $authUser = $this->user;


        $response = $this->actingAs($authUser)->get(route('member_password_edit', [$authUser]));

        $response->assertOk();
        $response->assertViewIs('member_password_edit');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
       // $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $authUser = $this->user;

        $response = $this->actingAs($authUser)->get(route('member', [$authUser]));

        $response->assertOk();
        $response->assertViewIs('member');
        $response->assertViewHas('data');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
       // $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $authUser = $this->user;

        //todo set up faker data to modify user for post

        $user = $this->user;

        $response = $this->actingAs($authUser)->post('member/{user}/edit', [
            // TODO: send request data


        ]);
//todo verify route
        $response->assertRedirect(route('member_edit', $authUser->id));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\UserController::class,
            'update',
            \App\Http\Requests\Member\UpdateMember::class
        );
    }

    /**
     * @test
     */
    public function update_address_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $authUser = \App\Models\User::factory()->create();

        $response = $this->actingAs($authUser)->post('member/{user}/address/edit', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('member_address_edit', $user->id));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_address_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\UserController::class,
            'update_address',
            \App\Http\Requests\User\UpdateMemberAddress::class
        );
    }

    /**
     * @test
     */
    public function update_emergency_contact_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $authUser = \App\Models\User::factory()->create();

        $response = $this->actingAs($authUser)->post('member/{user}/emergency_contact/edit', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('edit_emergency_contact', $user->id));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_emergency_contact_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\UserController::class,
            'update_emergency_contact',
            \App\Http\Requests\Member\UpdateMemberEmergencyContact::class
        );
    }

    /**
     * @test
     */
    public function update_password_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $authUser = \App\Models\User::factory()->create();

        $response = $this->actingAs($authUser)->post('member/{user}/password', [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('member_password_edit', $user->id));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_password_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\UserController::class,
            'update_password',
            \App\Http\Requests\InviteUser\ProcessUserRequest::class
        );
    }

    // test cases...
}
