<?php

namespace Tests\Unit\Http\Requests\User;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\User\UpdateUser
 */
class UpdateUserTest extends TestCase
{
    /** @var \App\Http\Requests\User\UpdateUser */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\User\UpdateUser();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'user.name' => 'required|string|max:255',
            'user_phone.phone_number' => 'max:20',
            'user_phone.label' => 'string|nullable',
            'user_phone.primary' => 'boolean',
            'user_info.share_email' => 'boolean',
            'user_info.share_phone' => 'boolean',
            'user_info.image' => 'string|nullable',
            'user_info.about' => 'string|nullable|max:2000',
            'user_roles' => 'array|required',
        ], $actual);
    }

    // test cases...
}
