<?php

namespace Tests\Unit\Http\Requests\Committees;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Committees\UpdateCommitteeRequest
 */
class UpdateCommitteeRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Committees\UpdateCommitteeRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Committees\UpdateCommitteeRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'committee.description' => 'required',
            'committee.email' => 'string|max:255',
            'committee.image' => 'file|nullable',
            'committee.live' => 'boolean',
        ], $actual);
    }

    // test cases...
}
