<?php

namespace Tests\Unit\Http\Requests\Agreements;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Agreements\UpdateAgreementRequest
 */
class UpdateAgreementRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Agreements\UpdateAgreementRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Agreements\UpdateAgreementRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'agreement.client' => 'array',
            'agreement.title' => 'required|max:255',
            'agreement.from' => 'required|date',
            'agreement.until' => 'required|date',
            'agreement.live' => 'boolean',
        ], $actual);
    }

    // test cases...
}
