
# Sample LEMP vhost file from VULTR. The default NGINX file is in /var/default-conf/nginx-vhost.conf

server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name iatse118.com www.iatse118.com;

	root /usr/share/nginx/html;
	index index.php index.html;
	try_files $uri $uri/ /index.php$is_args$args;
	# set max upload size
	client_max_body_size 4G;
	fastcgi_buffers 64 4K;

	server_tokens off;

	include /etc/nginx/site-extras/*.conf;

	access_log /var/log/nginx/http_access.log combined;
	error_log /var/log/nginx/http_error.log;

	location = /favicon.ico {
		log_not_found off;
		access_log off;
	}

	location = /robots.txt {
		allow all;
		log_not_found off;
		access_log off;
	}

	location ~ \.php$
	{
		try_files      $uri =404;
#		fastcgi_pass   127.0.0.1:9000;
# include snippets/fastcgi-php.conf;
		fastcgi_pass   unix:/var/run/php/php8.3-fpm.sock;
		fastcgi_index  index.php;
		fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
		include        fastcgi_params;
	}

	location ~* \.(htaccess|htpasswd) {
		deny all;
	}

	# set long EXPIRES header on static assets
	location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
		expires 30d;
		access_log off;
	}

}
