server {
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;
	server_name iatse118.com www.iatse118.com;

	ssl_certificate /etc/letsencrypt/live/iatse118.com/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/iatse118.com/privkey.pem; # managed by Certbot

	root /usr/share/nginx/html;
	index index.php index.html;

	try_files $uri $uri/ /index.php$is_args$args;

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";


	# set max upload size
	client_max_body_size 4G;
	fastcgi_buffers 64 4K;

	server_tokens off;

	include /etc/nginx/site-extras/*.conf;

	access_log /var/log/nginx/https_access.log combined;
	error_log /var/log/nginx/https_error.log;

	location = /favicon.ico {
		log_not_found off;
		access_log off;
	}

	location = /robots.txt {
		allow all;
		log_not_found off;
		access_log off;
	}

	location ~ \.php$
	{
		try_files      $uri =404;
		fastcgi_pass   unix:/var/run/php/php8.3-fpm.sock;
		fastcgi_index  index.php;
		fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
		include        fastcgi_params;
	}

	location ~* \.(htaccess|htpasswd) {
		deny all;
	}

	# set long EXPIRES header on static assets
	location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
		expires 30d;
		access_log off;
	}

}