<?php

namespace Tests\Unit\Http\Requests\Page;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Page\UpdatePageRequest
 */
class UpdatePageRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Page\UpdatePageRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Page\UpdatePageRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'page.content' => 'required',
            'page.access_level' => 'required|string|max:255',
            'page.live' => 'boolean',
            'page.front_page' => 'boolean',
            'page.landing_page' => 'boolean',
        ], $actual);
    }

    // test cases...
}
