<?php

namespace Tests\Unit\Http\Requests\Executive;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Executive\UpdateAdminExecutiveMembership
 */
class UpdateAdminExecutiveMembershipTest extends TestCase
{
    /** @var \App\Http\Requests\Executive\UpdateAdminExecutiveMembership */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Executive\UpdateAdminExecutiveMembership();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'executive.executive_id' => 'required',
            'executive.start_date' => 'date',
            'executive.end_date' => 'date',
        ], $actual);
    }

    // test cases...
}
